// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" }
import * as $0 from "./routes/api/auth.ts"
import * as $1 from "./routes/api/getUser.ts"
import * as $2 from "./routes/index.tsx"
import * as $3 from "./routes/user/[name].tsx"
import * as $$0 from "./islands/Counter.tsx"

const manifest = {
  routes: {
    "./routes/api/auth.ts": $0,
    "./routes/api/getUser.ts": $1,
    "./routes/index.tsx": $2,
    "./routes/user/[name].tsx": $3,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
  },
  baseUrl: import.meta.url,
  config,
}

export default manifest
